# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h-jwqiaSpUPLf6ZagqVCB9IBtI6QSC8d
"""

import cv2
import os
import subprocess  # For opening files on Mac

# Load the image
img = cv2.imread("flower.jpg")

# Get user input
msg = input("Enter secret message: ")
password = input("Enter a passcode: ")

# ASCII Mapping
d = {}
c = {}

for i in range(255):
    d[chr(i)] = i
    c[i] = chr(i)

# Encryption
n = 0
m = 0
z = 0

for i in range(len(msg)):
    img[n, m, z] = d[msg[i]]  # Embed message into pixels
    n += 1
    m += 1
    z = (z + 1) % 3  # Change RGB channel

# Save the encrypted image
cv2.imwrite("encryptedImage.jpg", img)

# Open the image based on OS
if os.name == "nt":  # Windows
    os.startfile("encryptedImage.jpg")
else:  # Mac/Linux
    subprocess.run(["open", "encryptedImage.jpg"])  # Mac (use "xdg-open" for Linux)

# Decryption
message = ""
n = 0
m = 0
z = 0

pas = input("Password for decryption: ")
if pas == password:
    for i in range(len(msg)):
        message += c[img[n, m, z]]  # Extract message from pixels
        n += 1
        m += 1
        z = (z + 1) % 3  # Change RGB channel

    print(f"Decrypted message: {message}")
else:
    print("Wrong password")
